set -sg escape-time 0
set -g mouse on
set -g renumber-windows on

# Toggle current panel to fullscreen, press it back to return it to the previous size
bind z resize-pane -Z

# AstroVim uses '\' for Vertical and '-' (or '|') for Horizontal
bind '|' split-window -h -c "#{pane_current_path}"
bind '\' split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Resize panels also on vim motions
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# --- Smart Pane Switching (Vim Awareness) ---
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

# Logic: If in Vim, send the key. 
# If NOT in Vim, only move if there is a pane in that direction (prevents wrap).
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' { if -F '#{pane_at_left}'   '' 'select-pane -L' }
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' { if -F '#{pane_at_bottom}' '' 'select-pane -D' }
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' { if -F '#{pane_at_top}'    '' 'select-pane -U' }
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' { if -F '#{pane_at_right}'  '' 'select-pane -R' }

